# Generated by Django 3.1.1 on 2020-09-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0002_auto_20200908_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='css',
            field=models.TextField(max_length=20000),
        ),
    ]
