# Generated by Django 3.1.1 on 2020-09-07 14:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('bullet_descript', models.CharField(blank=True, max_length=200)),
                ('descript', models.TextField(blank=True, max_length=500)),
                ('phone_num', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='0 ile başlayarak 11 haneli olarak giriniz.', regex='^\\d{11}$')])),
                ('address', models.CharField(blank=True, max_length=30)),
                ('links', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
